In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.array([2,3,5,6,7,8,12,15,16,31,45,32])

In [3]:
print(x)

[ 2  3  5  6  7  8 12 15 16 31 45 32]


In [4]:
np.array([2,3,5,6,7,8,12.6,15,16,31,45,32])

array([  2. ,   3. ,   5. ,   6. ,   7. ,   8. ,  12.6,  15. ,  16. ,
        31. ,  45. ,  32. ])

In [5]:
np.array([2,3,5,6,7,8,12.6,15,16,31,45,32,'hello'])

array(['2', '3', '5', '6', '7', '8', '12.6', '15', '16', '31', '45', '32',
       'hello'],
      dtype='<U32')

In [6]:
x = np.array([[3,4,5,6],[1,6,8,9],[32,45,78,90],[12,15,27,54]])

In [7]:
x

array([[ 3,  4,  5,  6],
       [ 1,  6,  8,  9],
       [32, 45, 78, 90],
       [12, 15, 27, 54]])

In [8]:
x[0]

array([3, 4, 5, 6])

In [9]:
x[0][1]

4

In [10]:
names = ['Ram','Shyam','Manoj','Anuj','Ravi','Rohan','Raman']

In [11]:
names[0]

'Ram'

In [12]:
names[-1]

'Raman'

In [13]:
names[0:3]

['Ram', 'Shyam', 'Manoj']

In [14]:
names[3]

'Anuj'

In [15]:
names[3:0]

[]

In [16]:
names[0:5:1]

['Ram', 'Shyam', 'Manoj', 'Anuj', 'Ravi']

In [17]:
names[0:5:2]

['Ram', 'Manoj', 'Ravi']

In [18]:
names[5:1:-1]

['Rohan', 'Ravi', 'Anuj', 'Manoj']

In [19]:
x

array([[ 3,  4,  5,  6],
       [ 1,  6,  8,  9],
       [32, 45, 78, 90],
       [12, 15, 27, 54]])

In [20]:
x[0:2]

array([[3, 4, 5, 6],
       [1, 6, 8, 9]])

In [21]:
x[0:2, 0:2]

array([[3, 4],
       [1, 6]])

In [22]:
x[:, 0:1]

array([[ 3],
       [ 1],
       [32],
       [12]])

In [23]:
x.shape

(4, 4)

In [24]:
x.reshape(8,2)

array([[ 3,  4],
       [ 5,  6],
       [ 1,  6],
       [ 8,  9],
       [32, 45],
       [78, 90],
       [12, 15],
       [27, 54]])